name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '30 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update repository
        run: |
          cd $GITHUB_WORKSPACE
          git config user.email "robot@firefly-iii.org"
          git config user.name "Firefly III build robot"
          echo $(date '+%d-%m-%Y %T %Z') > date.txt
          git add date.txt
          git commit -m "Auto commit on $(date '+%d-%m-%Y') [skip ci]"
          git push
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run script
        run: |
          php new-releases.php
        env:
          MASTODON_URL: ${{ secrets.MASTODON_URL }}
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
      - name: "Commit new file(s) to this repository"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add cache/releases.json
          git add site/index.json
          git commit -m "Auto-update for new version on $(date '+%d-%m-%Y')" || true
          git push || true
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: aaf8eef9dd565a13de210d18c7462092
          projectName: version
          directory: site
          wranglerVersion: '3'
